echo 'memory_size;n_producers;n_consumers;time_elapsed' > pc-time.csv
echo '[-] Generating CSV Files'
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 1 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 2 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 4 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 16 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 2 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 2 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 8 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 8 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 4 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 1 16 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 4 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo "$(./producer-consumer 32 16 1 | grep final | awk '{print $NF}')" >> pc-time.csv
echo '[X] Generated'
